# Package Overview
package_name: regression_model

# Data Files
raw_data_file: raw_dataset.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

# variables_to_rename:
#   home.dest: address

features:
  - pclass
  - survived
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title

# set train/test split
test_size: 0.12

# to set the random seed
random_state: 0

alpha: 0.001

unused_fields:
  - name
  - ticket
  - boat
  - body
  - home.dest

numerical_vars:
  - age
  - fare

categorical_vars:
  - sex
  - cabin
  - embarked
  - title

cabin_vars:
  - cabin